version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.0-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      ##- node/install-packages:
      ##    pkg-manager: yarn
      ##    cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.2.0-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      #PGHOST: 127.0.0.1
      #PGUSER: circleci-demo-ruby
      #PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      ##- node/install-packages:
      ##    pkg-manager: yarn
      ##    cache-key: "yarn.lock"
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
