#!/usr/bin/env bun
// Regenerates src/data/projects.ts from GitHub. Run manually (`bun run
// sync:projects`) rather than at request time: the site then has no runtime
// dependency on GitHub, no rate limit exposure, and the data stays reviewable
// in git.
//
// Requires the `gh` CLI, authenticated. Edit SKIP or MIN_SIGNAL below to change
// which repos qualify; hand-edits to the generated file are lost on re-run.

import { writeFileSync } from 'node:fs'

const OWNER = 'docimin'
const OUT = new URL('../src/data/projects.ts', import.meta.url).pathname

// Scratch, repro and profile repos that are not portfolio pieces.
const SKIP = new Set([
  'docimin',
  'Testing',
  'openai',
  'test-nuxt',
  'sentry-repro-bun',
  'experimental-ubuntu',
  'slider-gsap',
])

type Repo = {
  name: string
  private: boolean
  fork: boolean
  archived: boolean
  description: string | null
  homepage: string | null
  default_branch: string
  created_at: string
  pushed_at: string
  html_url: string
  stargazers_count: number
}

// A repo earns a slot by showing it was meant for someone else to see.
const MIN_SIGNAL = (repo: Repo) =>
  Boolean(repo.description) ||
  Boolean(repo.homepage) ||
  repo.stargazers_count > 0

function statusFor(repo: Repo): string {
  if (repo.archived) return 'Archived'
  const monthsIdle =
    (Date.now() - new Date(repo.pushed_at).getTime()) /
    (1000 * 60 * 60 * 24 * 30)
  if (monthsIdle > 12) return 'Paused'
  if (repo.homepage) return 'Online'
  return 'Ongoing'
}

const raw = await new Response(
  Bun.spawn([
    'gh',
    'api',
    `users/${OWNER}/repos?per_page=100&sort=pushed`,
    '--paginate',
  ]).stdout
).text()

const repos: Repo[] = JSON.parse(raw)

const selected = repos
  .filter(
    (repo) =>
      !repo.fork && !repo.private && !SKIP.has(repo.name) && MIN_SIGNAL(repo)
  )
  .sort((a, b) => b.stargazers_count - a.stargazers_count)

const rows = selected
  .map((repo) => {
    const fields = [
      `    name: ${JSON.stringify(repo.name)},`,
      `    status: ${JSON.stringify(statusFor(repo))},`,
      `    gitRepo: ${JSON.stringify(repo.html_url)},`,
      `    branch: ${JSON.stringify(repo.default_branch)},`,
      repo.homepage ? `    customUrl: ${JSON.stringify(repo.homepage)},` : null,
      `    private: false,`,
      `    createdAt: ${JSON.stringify(repo.created_at.slice(0, 10))},`,
    ].filter(Boolean)
    return `  {\n${fields.join('\n')}\n  },`
  })
  .join('\n')

const source = `// Generated by scripts/sync-projects.ts - run \`bun run sync:projects\` to refresh.
// Hand edits are overwritten. Change the SKIP list or MIN_SIGNAL in that script
// to control which repos appear.

export type ProjectStatus =
  | 'Ongoing'
  | 'Maintenance'
  | 'Pending'
  | 'Completed'
  | 'Online'
  | 'Error'
  | 'Paused'
  | 'Archived'

export type Project = {
  name: string
  status: ProjectStatus
  gitRepo?: string
  branch?: string
  customUrl?: string
  private: boolean
  image?: string
  createdAt: string
}

export const STATUS_ORDER: ProjectStatus[] = [
  'Ongoing',
  'Maintenance',
  'Pending',
  'Completed',
  'Online',
  'Error',
  'Paused',
  'Archived',
]

export const STATUS_CLASS: Record<ProjectStatus, string> = {
  Ongoing: 'text-yellow-400 bg-yellow-400/10',
  Maintenance: 'text-yellow-400 bg-yellow-400/10',
  Pending: 'text-red-400 bg-red-400/10',
  Completed: 'text-green-400 bg-green-400/10',
  Online: 'text-green-400 bg-green-400/10',
  Error: 'text-rose-400 bg-rose-400/10',
  Paused: 'text-gray-400 bg-gray-400/10',
  Archived: 'text-orange-400 bg-orange-400/10',
}

export const PROJECTS: Project[] = [
${rows}
]

export function sortProjects(projects: Project[]): Project[] {
  return [...projects].sort((a, b) => {
    const rank = STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status)
    return rank !== 0 ? rank : a.name.localeCompare(b.name)
  })
}
`

writeFileSync(OUT, source)

// Biome owns formatting; without this the generated file fails `bun run lint`.
await Bun.spawn(['bunx', 'biome', 'format', '--write', OUT]).exited

console.log(`wrote ${selected.length} projects to ${OUT}`)
for (const repo of selected) {
  console.log(`  ${repo.name} (${statusFor(repo)})`)
}
