// Generated by scripts/sync-projects.ts - run `bun run sync:projects` to refresh.
// Hand edits are overwritten. Change the SKIP list or MIN_SIGNAL in that script
// to control which repos appear.

export type ProjectStatus =
  | 'Ongoing'
  | 'Maintenance'
  | 'Pending'
  | 'Completed'
  | 'Online'
  | 'Error'
  | 'Paused'
  | 'Archived'

export type Project = {
  name: string
  status: ProjectStatus
  gitRepo?: string
  branch?: string
  customUrl?: string
  private: boolean
  image?: string
  createdAt: string
}

export const STATUS_ORDER: ProjectStatus[] = [
  'Ongoing',
  'Maintenance',
  'Pending',
  'Completed',
  'Online',
  'Error',
  'Paused',
  'Archived',
]

export const STATUS_CLASS: Record<ProjectStatus, string> = {
  Ongoing: 'text-yellow-400 bg-yellow-400/10',
  Maintenance: 'text-yellow-400 bg-yellow-400/10',
  Pending: 'text-red-400 bg-red-400/10',
  Completed: 'text-green-400 bg-green-400/10',
  Online: 'text-green-400 bg-green-400/10',
  Error: 'text-rose-400 bg-rose-400/10',
  Paused: 'text-gray-400 bg-gray-400/10',
  Archived: 'text-orange-400 bg-orange-400/10',
}

export const PROJECTS: Project[] = [
  {
    name: 'cloudnet-webinterface',
    status: 'Online',
    gitRepo: 'https://github.com/docimin/cloudnet-webinterface',
    branch: 'main',
    customUrl: 'https://cloudnet.fayevr.dev/',
    private: false,
    createdAt: '2023-07-04',
  },
  {
    name: 'liftoff',
    status: 'Ongoing',
    gitRepo: 'https://github.com/docimin/liftoff',
    branch: 'main',
    private: false,
    createdAt: '2026-04-07',
  },
  {
    name: 'modmail-bot',
    status: 'Ongoing',
    gitRepo: 'https://github.com/docimin/modmail-bot',
    branch: 'main',
    private: false,
    createdAt: '2022-06-24',
  },
  {
    name: 'emblor',
    status: 'Paused',
    gitRepo: 'https://github.com/docimin/emblor',
    branch: 'main',
    customUrl: 'https://fayevr.dev/registry/emblor.json',
    private: false,
    createdAt: '2025-06-13',
  },
  {
    name: 'qr-generator',
    status: 'Online',
    gitRepo: 'https://github.com/docimin/qr-generator',
    branch: 'main',
    customUrl: 'https://qr-generator.dev/',
    private: false,
    createdAt: '2025-08-14',
  },
  {
    name: 'fayevr.dev',
    status: 'Online',
    gitRepo: 'https://github.com/docimin/fayevr.dev',
    branch: 'main',
    customUrl: 'https://fayevr.dev',
    private: false,
    createdAt: '2022-06-23',
  },
  {
    name: 'music-vrcosc',
    status: 'Ongoing',
    gitRepo: 'https://github.com/docimin/music-vrcosc',
    branch: 'main',
    private: false,
    createdAt: '2026-04-12',
  },
]

export function sortProjects(projects: Project[]): Project[] {
  return [...projects].sort((a, b) => {
    const rank = STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status)
    return rank !== 0 ? rank : a.name.localeCompare(b.name)
  })
}
