name: Build and Push Next.js to Harbor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and install dependencies with pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Replace with the Node.js version your project requires
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          corepack enable
          pnpm install

      # Step 3: Build the Next.js project
      - name: Build Project
        run: pnpm build

      # Step 4: Prepare the Docker image
      - name: Log in to Harbor
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.fayevr.dev -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          echo "FROM node:18-alpine" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY .next /app/.next" >> Dockerfile
          echo "COPY package.json pnpm-lock.yaml /app/" >> Dockerfile
          echo "RUN npm install -g corepack && corepack enable && pnpm install --prod" >> Dockerfile
          echo "EXPOSE 3000" >> Dockerfile
          echo "CMD [\"pnpm\", \"start\"]" >> Dockerfile

          docker build -t harbor.fayevr.dev/fleet/fayevr.dev:latest .

      # Step 5: Push the Docker image to Harbor
      - name: Push Docker Image
        run: docker push harbor.fayevr.dev/fleet/fayevr.dev:latest
