name: Build and Push Next.js to Harbor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env: # Env variables needed during build
      NEXT_PUBLIC_DOMAIN_BACKEND: ${{secrets.NEXT_PUBLIC_DOMAIN_BACKEND}}
      NEXT_PUBLIC_PROJECT_ID: ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
      API_KEY: ${{secrets.API_KEY}}

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and install dependencies with pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      # Step 3: Build the Next.js project
      - name: Build Project
        run: pnpm build

      # Step 4: Prepare the Docker image
      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.fayevr.dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: harbor.fayevr.dev/fleet/fayevr.dev:latest
          build-args: |
              NEXT_PUBLIC_DOMAIN_BACKEND=$NEXT_PUBLIC_DOMAIN_BACKEND
              NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID
              API_KEY=$API_KEY
