name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Harbor Registry
      - name: Log in to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: harbor.fayevr.dev
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_DOMAIN_BACKEND=${{ secrets.NEXT_PUBLIC_DOMAIN_BACKEND }} \
            --build-arg NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }} \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            -t harbor.fayevr.dev/fleet/nextjs-app:latest .
          docker push harbor.fayevr.dev/fleet/nextjs-app:latest